###############################################ПОЛЬЗОВАТЕЛИ#############################################################

### Регистрация нового пользователя
POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "sakharov_mikhail@hotmail.com",
  "userName": "Mikhail",
  "password": "123456"
}
### Вход
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "sakharov_mikhail@hotmail.com",
  "password": "123456"
}
### Проверка авторизации
GET http://localhost:3000/users/checkAuth HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNha2hhcm92X21pa2hhaWxAaG90bWFpbC5jb20iLCJpZCI6IjYzZWY4NWFiYWQ3MGM1ZDJhNjVkNTdmYyIsImlhdCI6MTY3NjY0MjA0OCwiZXhwIjoxNjc2ODE0ODQ4fQ.Fm1DjXLvrzLFdM03sLTprATV7dfECf3e1Dq4G65KGVY

#################################################ПРОДУКТЫ################################################################

### Запрос всех продуктов
GET http://localhost:3000/products HTTP/1.1
### Запрос детальной информации по id
GET http://localhost:3000/products/63f058ebd71c452da6bf8bf2 HTTP/1.1
### Запрос с параметром stringsCount
GET http://localhost:3000/products?stringsCount=12,6 HTTP/1.1
### Запрос с параметром guitarType
GET http://localhost:3000/products?guitarType=укулеле,электро HTTP/1.1
### Запрос с комбинированными параметрами
GET http://localhost:3000/products?stringsCount=7,6&guitarType=аккустика HTTP/1.1
### Создание карточки продукта
POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNha2hhcm92X21pa2hhaWxAaG90bWFpbC5jb20iLCJpZCI6IjYzZWY4NWFiYWQ3MGM1ZDJhNjVkNTdmYyIsImlhdCI6MTY3NjY0MjA0OCwiZXhwIjoxNjc2ODE0ODQ4fQ.Fm1DjXLvrzLFdM03sLTprATV7dfECf3e1Dq4G65KGVY

{
  "createdAt": "2023-02-17T13:48:27.653Z",
  "authorId": "63ef85abad70c5d2a65d57fc",
  "title": "Fender DB-987345-q98",
  "description": "The best guitar ever!!!!!!!!!!!!!!!!!",
  "image": "guitar.jpg",
  "guitarType": "электро",
  "sku": "123qwe456rty-102",
  "stringsCount": 12,
  "price": 45990
}

#################################################ЗАКАЗЫ################################################################

### Создание заказа
POST http://localhost:3000/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNha2hhcm92X21pa2hhaWxAaG90bWFpbC5jb20iLCJpZCI6IjYzZjI0NmMxZDQxOGQ5ZmEwNDU5ZmEzZiIsImlhdCI6MTY3NjgyMjIxMiwiZXhwIjoxNjc2OTk1MDEyfQ.6c1rXrfOVAMQ58dJQbtvUKjvFe9moZ5CvGkwUE5v-qs

{
  "items": [
    {
      "productId": "63f1103012f60ca02937e575",
      "quantity": 3,
      "totalOrderPrice": 1782420
    },
    {
      "productId": "63f1103012f60ca02937e57f",
      "quantity": 2,
      "totalOrderPrice": 1200358
    }
  ],
  "userId": "63f1103012f60ca02937e579",
  "totalOrderPrice": 2982778
}

### Запрос всех заказов
GET http://localhost:3000/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNha2hhcm92X21pa2hhaWxAaG90bWFpbC5jb20iLCJpZCI6IjYzZjI0NmMxZDQxOGQ5ZmEwNDU5ZmEzZiIsImlhdCI6MTY3NjgyMjIxMiwiZXhwIjoxNjc2OTk1MDEyfQ.6c1rXrfOVAMQ58dJQbtvUKjvFe9moZ5CvGkwUE5v-qs




###
POST http://localhost:5555/products/6359642bf9e16d7987d855b9/preview HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Inp4Y3ZibkB6eGN2Ym4uY29tIiwiaWQiOiI2MzU4MjZhN2NlM2NjNjdkMWQzNWQyNDAiLCJpYXQiOjE2NjY3ODcwNjIsImV4cCI6MTY2Njk1OTg2Mn0.xkmIEWt7w0fyIISuOQ-YZ7L6mEcCo5i48XxOBDfGXiI

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="preview"; filename="room.jpg"
Content-Type: image/jpeg

< ./markup/img/room.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
